(cl:in-package grapebot_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          STEERANGLECOMMAND-VAL
          STEERANGLECOMMAND
          STEERANGLERESPONSE-VAL
          STEERANGLERESPONSE
          LINEARVELOCITYCOMMAND-VAL
          LINEARVELOCITYCOMMAND
          LEFTWHEELVELOCITYCOMMAND-VAL
          LEFTWHEELVELOCITYCOMMAND
          RIGHTWHEELVELOCITYCOMMAND-VAL
          RIGHTWHEELVELOCITYCOMMAND
          FRONTWHEELVELOCITYCOMMAND-VAL
          FRONTWHEELVELOCITYCOMMAND
          LINEARVELOCITYRESPONSE-VAL
          LINEARVELOCITYRESPONSE
          LEFTWHEELVELOCITYRESPONSE-VAL
          LEFTWHEELVELOCITYRESPONSE
          RIGHTWHEELVELOCITYRESPONSE-VAL
          RIGHTWHEELVELOCITYRESPONSE
          FRONTWHEELVELOCITYRESPONSE-VAL
          FRONTWHEELVELOCITYRESPONSE
))