// Generated by gencpp from file grapebot_msgs/ControlCommand.msg
// DO NOT EDIT!


#ifndef GRAPEBOT_MSGS_MESSAGE_CONTROLCOMMAND_H
#define GRAPEBOT_MSGS_MESSAGE_CONTROLCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace grapebot_msgs
{
template <class ContainerAllocator>
struct ControlCommand_
{
  typedef ControlCommand_<ContainerAllocator> Type;

  ControlCommand_()
    : header()
    , linearVelocity(0.0)
    , angularVelocity(0.0)
    , steeringAngle(0.0)
    , controlMode(0)
    , robotStop(false)  {
    }
  ControlCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , linearVelocity(0.0)
    , angularVelocity(0.0)
    , steeringAngle(0.0)
    , controlMode(0)
    , robotStop(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _linearVelocity_type;
  _linearVelocity_type linearVelocity;

   typedef float _angularVelocity_type;
  _angularVelocity_type angularVelocity;

   typedef float _steeringAngle_type;
  _steeringAngle_type steeringAngle;

   typedef int16_t _controlMode_type;
  _controlMode_type controlMode;

   typedef uint8_t _robotStop_type;
  _robotStop_type robotStop;





  typedef boost::shared_ptr< ::grapebot_msgs::ControlCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grapebot_msgs::ControlCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ControlCommand_

typedef ::grapebot_msgs::ControlCommand_<std::allocator<void> > ControlCommand;

typedef boost::shared_ptr< ::grapebot_msgs::ControlCommand > ControlCommandPtr;
typedef boost::shared_ptr< ::grapebot_msgs::ControlCommand const> ControlCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grapebot_msgs::ControlCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grapebot_msgs::ControlCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grapebot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'grapebot_msgs': ['/home/pc/grapebot_simulation/catkin_ws/src/grapebot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grapebot_msgs::ControlCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grapebot_msgs::ControlCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grapebot_msgs::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grapebot_msgs::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grapebot_msgs::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grapebot_msgs::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grapebot_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d93c5b5e27556bc38e51f13b2d85f1fa";
  }

  static const char* value(const ::grapebot_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd93c5b5e27556bc3ULL;
  static const uint64_t static_value2 = 0x8e51f13b2d85f1faULL;
};

template<class ContainerAllocator>
struct DataType< ::grapebot_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grapebot_msgs/ControlCommand";
  }

  static const char* value(const ::grapebot_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grapebot_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 linearVelocity\n\
float32 angularVelocity\n\
float32 steeringAngle\n\
int16 controlMode\n\
bool robotStop\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::grapebot_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grapebot_msgs::ControlCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.linearVelocity);
      stream.next(m.angularVelocity);
      stream.next(m.steeringAngle);
      stream.next(m.controlMode);
      stream.next(m.robotStop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grapebot_msgs::ControlCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grapebot_msgs::ControlCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "linearVelocity: ";
    Printer<float>::stream(s, indent + "  ", v.linearVelocity);
    s << indent << "angularVelocity: ";
    Printer<float>::stream(s, indent + "  ", v.angularVelocity);
    s << indent << "steeringAngle: ";
    Printer<float>::stream(s, indent + "  ", v.steeringAngle);
    s << indent << "controlMode: ";
    Printer<int16_t>::stream(s, indent + "  ", v.controlMode);
    s << indent << "robotStop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.robotStop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPEBOT_MSGS_MESSAGE_CONTROLCOMMAND_H
