// Generated by gencpp from file grapebot_msgs/ControlState.msg
// DO NOT EDIT!


#ifndef GRAPEBOT_MSGS_MESSAGE_CONTROLSTATE_H
#define GRAPEBOT_MSGS_MESSAGE_CONTROLSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace grapebot_msgs
{
template <class ContainerAllocator>
struct ControlState_
{
  typedef ControlState_<ContainerAllocator> Type;

  ControlState_()
    : header()
    , SteerAngleCommand(0.0)
    , SteerAngleResponse(0.0)
    , linearVelocityCommand(0.0)
    , leftWheelVelocityCommand(0.0)
    , rightWheelVelocityCommand(0.0)
    , frontWheelVelocityCommand(0.0)
    , linearVelocityResponse(0.0)
    , leftWheelVelocityResponse(0.0)
    , rightWheelVelocityResponse(0.0)
    , frontWheelVelocityResponse(0.0)  {
    }
  ControlState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , SteerAngleCommand(0.0)
    , SteerAngleResponse(0.0)
    , linearVelocityCommand(0.0)
    , leftWheelVelocityCommand(0.0)
    , rightWheelVelocityCommand(0.0)
    , frontWheelVelocityCommand(0.0)
    , linearVelocityResponse(0.0)
    , leftWheelVelocityResponse(0.0)
    , rightWheelVelocityResponse(0.0)
    , frontWheelVelocityResponse(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _SteerAngleCommand_type;
  _SteerAngleCommand_type SteerAngleCommand;

   typedef float _SteerAngleResponse_type;
  _SteerAngleResponse_type SteerAngleResponse;

   typedef float _linearVelocityCommand_type;
  _linearVelocityCommand_type linearVelocityCommand;

   typedef float _leftWheelVelocityCommand_type;
  _leftWheelVelocityCommand_type leftWheelVelocityCommand;

   typedef float _rightWheelVelocityCommand_type;
  _rightWheelVelocityCommand_type rightWheelVelocityCommand;

   typedef float _frontWheelVelocityCommand_type;
  _frontWheelVelocityCommand_type frontWheelVelocityCommand;

   typedef float _linearVelocityResponse_type;
  _linearVelocityResponse_type linearVelocityResponse;

   typedef float _leftWheelVelocityResponse_type;
  _leftWheelVelocityResponse_type leftWheelVelocityResponse;

   typedef float _rightWheelVelocityResponse_type;
  _rightWheelVelocityResponse_type rightWheelVelocityResponse;

   typedef float _frontWheelVelocityResponse_type;
  _frontWheelVelocityResponse_type frontWheelVelocityResponse;





  typedef boost::shared_ptr< ::grapebot_msgs::ControlState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grapebot_msgs::ControlState_<ContainerAllocator> const> ConstPtr;

}; // struct ControlState_

typedef ::grapebot_msgs::ControlState_<std::allocator<void> > ControlState;

typedef boost::shared_ptr< ::grapebot_msgs::ControlState > ControlStatePtr;
typedef boost::shared_ptr< ::grapebot_msgs::ControlState const> ControlStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grapebot_msgs::ControlState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grapebot_msgs::ControlState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grapebot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'grapebot_msgs': ['/home/pc/grapebot_simulation/catkin_ws/src/grapebot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grapebot_msgs::ControlState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grapebot_msgs::ControlState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grapebot_msgs::ControlState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grapebot_msgs::ControlState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grapebot_msgs::ControlState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grapebot_msgs::ControlState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grapebot_msgs::ControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "349f39f889b30f99304b05f07b1445d7";
  }

  static const char* value(const ::grapebot_msgs::ControlState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x349f39f889b30f99ULL;
  static const uint64_t static_value2 = 0x304b05f07b1445d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::grapebot_msgs::ControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grapebot_msgs/ControlState";
  }

  static const char* value(const ::grapebot_msgs::ControlState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grapebot_msgs::ControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float32 SteerAngleCommand\n\
float32 SteerAngleResponse\n\
\n\
float32 linearVelocityCommand\n\
float32 leftWheelVelocityCommand\n\
float32 rightWheelVelocityCommand\n\
float32 frontWheelVelocityCommand\n\
float32 linearVelocityResponse\n\
float32 leftWheelVelocityResponse\n\
float32 rightWheelVelocityResponse\n\
float32 frontWheelVelocityResponse\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::grapebot_msgs::ControlState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grapebot_msgs::ControlState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.SteerAngleCommand);
      stream.next(m.SteerAngleResponse);
      stream.next(m.linearVelocityCommand);
      stream.next(m.leftWheelVelocityCommand);
      stream.next(m.rightWheelVelocityCommand);
      stream.next(m.frontWheelVelocityCommand);
      stream.next(m.linearVelocityResponse);
      stream.next(m.leftWheelVelocityResponse);
      stream.next(m.rightWheelVelocityResponse);
      stream.next(m.frontWheelVelocityResponse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grapebot_msgs::ControlState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grapebot_msgs::ControlState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "SteerAngleCommand: ";
    Printer<float>::stream(s, indent + "  ", v.SteerAngleCommand);
    s << indent << "SteerAngleResponse: ";
    Printer<float>::stream(s, indent + "  ", v.SteerAngleResponse);
    s << indent << "linearVelocityCommand: ";
    Printer<float>::stream(s, indent + "  ", v.linearVelocityCommand);
    s << indent << "leftWheelVelocityCommand: ";
    Printer<float>::stream(s, indent + "  ", v.leftWheelVelocityCommand);
    s << indent << "rightWheelVelocityCommand: ";
    Printer<float>::stream(s, indent + "  ", v.rightWheelVelocityCommand);
    s << indent << "frontWheelVelocityCommand: ";
    Printer<float>::stream(s, indent + "  ", v.frontWheelVelocityCommand);
    s << indent << "linearVelocityResponse: ";
    Printer<float>::stream(s, indent + "  ", v.linearVelocityResponse);
    s << indent << "leftWheelVelocityResponse: ";
    Printer<float>::stream(s, indent + "  ", v.leftWheelVelocityResponse);
    s << indent << "rightWheelVelocityResponse: ";
    Printer<float>::stream(s, indent + "  ", v.rightWheelVelocityResponse);
    s << indent << "frontWheelVelocityResponse: ";
    Printer<float>::stream(s, indent + "  ", v.frontWheelVelocityResponse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPEBOT_MSGS_MESSAGE_CONTROLSTATE_H
