// Generated by gencpp from file grapebot_msgs/OdomError.msg
// DO NOT EDIT!


#ifndef GRAPEBOT_MSGS_MESSAGE_ODOMERROR_H
#define GRAPEBOT_MSGS_MESSAGE_ODOMERROR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace grapebot_msgs
{
template <class ContainerAllocator>
struct OdomError_
{
  typedef OdomError_<ContainerAllocator> Type;

  OdomError_()
    : header()
    , xError(0.0)
    , yError(0.0)
    , thetaError(0.0)
    , vxError(0.0)
    , vyError(0.0)
    , angularVelocityError(0.0)
    , linearVelocityError(0.0)  {
    }
  OdomError_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , xError(0.0)
    , yError(0.0)
    , thetaError(0.0)
    , vxError(0.0)
    , vyError(0.0)
    , angularVelocityError(0.0)
    , linearVelocityError(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _xError_type;
  _xError_type xError;

   typedef double _yError_type;
  _yError_type yError;

   typedef double _thetaError_type;
  _thetaError_type thetaError;

   typedef double _vxError_type;
  _vxError_type vxError;

   typedef double _vyError_type;
  _vyError_type vyError;

   typedef double _angularVelocityError_type;
  _angularVelocityError_type angularVelocityError;

   typedef double _linearVelocityError_type;
  _linearVelocityError_type linearVelocityError;





  typedef boost::shared_ptr< ::grapebot_msgs::OdomError_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grapebot_msgs::OdomError_<ContainerAllocator> const> ConstPtr;

}; // struct OdomError_

typedef ::grapebot_msgs::OdomError_<std::allocator<void> > OdomError;

typedef boost::shared_ptr< ::grapebot_msgs::OdomError > OdomErrorPtr;
typedef boost::shared_ptr< ::grapebot_msgs::OdomError const> OdomErrorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grapebot_msgs::OdomError_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grapebot_msgs::OdomError_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grapebot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'grapebot_msgs': ['/home/pc/grapebot_simulation/catkin_ws/src/grapebot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grapebot_msgs::OdomError_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grapebot_msgs::OdomError_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grapebot_msgs::OdomError_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grapebot_msgs::OdomError_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grapebot_msgs::OdomError_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grapebot_msgs::OdomError_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grapebot_msgs::OdomError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f07c711d610abd5fe2a2b6e0224c4ac";
  }

  static const char* value(const ::grapebot_msgs::OdomError_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f07c711d610abd5ULL;
  static const uint64_t static_value2 = 0xfe2a2b6e0224c4acULL;
};

template<class ContainerAllocator>
struct DataType< ::grapebot_msgs::OdomError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grapebot_msgs/OdomError";
  }

  static const char* value(const ::grapebot_msgs::OdomError_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grapebot_msgs::OdomError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 xError\n\
float64 yError\n\
float64 thetaError\n\
float64 vxError\n\
float64 vyError\n\
float64 angularVelocityError\n\
float64 linearVelocityError\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::grapebot_msgs::OdomError_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grapebot_msgs::OdomError_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.xError);
      stream.next(m.yError);
      stream.next(m.thetaError);
      stream.next(m.vxError);
      stream.next(m.vyError);
      stream.next(m.angularVelocityError);
      stream.next(m.linearVelocityError);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdomError_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grapebot_msgs::OdomError_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grapebot_msgs::OdomError_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "xError: ";
    Printer<double>::stream(s, indent + "  ", v.xError);
    s << indent << "yError: ";
    Printer<double>::stream(s, indent + "  ", v.yError);
    s << indent << "thetaError: ";
    Printer<double>::stream(s, indent + "  ", v.thetaError);
    s << indent << "vxError: ";
    Printer<double>::stream(s, indent + "  ", v.vxError);
    s << indent << "vyError: ";
    Printer<double>::stream(s, indent + "  ", v.vyError);
    s << indent << "angularVelocityError: ";
    Printer<double>::stream(s, indent + "  ", v.angularVelocityError);
    s << indent << "linearVelocityError: ";
    Printer<double>::stream(s, indent + "  ", v.linearVelocityError);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPEBOT_MSGS_MESSAGE_ODOMERROR_H
