// Generated by gencpp from file grapebot_msgs/PIDSteerState.msg
// DO NOT EDIT!


#ifndef GRAPEBOT_MSGS_MESSAGE_PIDSTEERSTATE_H
#define GRAPEBOT_MSGS_MESSAGE_PIDSTEERSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace grapebot_msgs
{
template <class ContainerAllocator>
struct PIDSteerState_
{
  typedef PIDSteerState_<ContainerAllocator> Type;

  PIDSteerState_()
    : header()
    , p_error(0.0)
    , i_error(0.0)
    , d_error(0.0)
    , control_response(0.0)
    , set_point(0.0)  {
    }
  PIDSteerState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , p_error(0.0)
    , i_error(0.0)
    , d_error(0.0)
    , control_response(0.0)
    , set_point(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _p_error_type;
  _p_error_type p_error;

   typedef double _i_error_type;
  _i_error_type i_error;

   typedef double _d_error_type;
  _d_error_type d_error;

   typedef double _control_response_type;
  _control_response_type control_response;

   typedef double _set_point_type;
  _set_point_type set_point;





  typedef boost::shared_ptr< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> const> ConstPtr;

}; // struct PIDSteerState_

typedef ::grapebot_msgs::PIDSteerState_<std::allocator<void> > PIDSteerState;

typedef boost::shared_ptr< ::grapebot_msgs::PIDSteerState > PIDSteerStatePtr;
typedef boost::shared_ptr< ::grapebot_msgs::PIDSteerState const> PIDSteerStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grapebot_msgs::PIDSteerState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grapebot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'grapebot_msgs': ['/home/pc/grapebot_simulation/catkin_ws/src/grapebot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6d443c27b96bf6a06d83f395d0cd761";
  }

  static const char* value(const ::grapebot_msgs::PIDSteerState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6d443c27b96bf6aULL;
  static const uint64_t static_value2 = 0x06d83f395d0cd761ULL;
};

template<class ContainerAllocator>
struct DataType< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grapebot_msgs/PIDSteerState";
  }

  static const char* value(const ::grapebot_msgs::PIDSteerState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 p_error\n\
float64 i_error\n\
float64 d_error\n\
float64 control_response\n\
float64 set_point\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::grapebot_msgs::PIDSteerState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.p_error);
      stream.next(m.i_error);
      stream.next(m.d_error);
      stream.next(m.control_response);
      stream.next(m.set_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PIDSteerState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grapebot_msgs::PIDSteerState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grapebot_msgs::PIDSteerState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "p_error: ";
    Printer<double>::stream(s, indent + "  ", v.p_error);
    s << indent << "i_error: ";
    Printer<double>::stream(s, indent + "  ", v.i_error);
    s << indent << "d_error: ";
    Printer<double>::stream(s, indent + "  ", v.d_error);
    s << indent << "control_response: ";
    Printer<double>::stream(s, indent + "  ", v.control_response);
    s << indent << "set_point: ";
    Printer<double>::stream(s, indent + "  ", v.set_point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPEBOT_MSGS_MESSAGE_PIDSTEERSTATE_H
