// Generated by gencpp from file grapebot_msgs/SteerState.msg
// DO NOT EDIT!


#ifndef GRAPEBOT_MSGS_MESSAGE_STEERSTATE_H
#define GRAPEBOT_MSGS_MESSAGE_STEERSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace grapebot_msgs
{
template <class ContainerAllocator>
struct SteerState_
{
  typedef SteerState_<ContainerAllocator> Type;

  SteerState_()
    : header()
    , CurrentSteerAngle(0.0)
    , CurrentSensorRead(0.0)  {
    }
  SteerState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , CurrentSteerAngle(0.0)
    , CurrentSensorRead(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _CurrentSteerAngle_type;
  _CurrentSteerAngle_type CurrentSteerAngle;

   typedef float _CurrentSensorRead_type;
  _CurrentSensorRead_type CurrentSensorRead;





  typedef boost::shared_ptr< ::grapebot_msgs::SteerState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grapebot_msgs::SteerState_<ContainerAllocator> const> ConstPtr;

}; // struct SteerState_

typedef ::grapebot_msgs::SteerState_<std::allocator<void> > SteerState;

typedef boost::shared_ptr< ::grapebot_msgs::SteerState > SteerStatePtr;
typedef boost::shared_ptr< ::grapebot_msgs::SteerState const> SteerStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grapebot_msgs::SteerState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grapebot_msgs::SteerState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grapebot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'grapebot_msgs': ['/home/pc/grapebot_simulation/catkin_ws/src/grapebot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grapebot_msgs::SteerState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grapebot_msgs::SteerState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grapebot_msgs::SteerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grapebot_msgs::SteerState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grapebot_msgs::SteerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grapebot_msgs::SteerState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grapebot_msgs::SteerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95d8e1b9d99823009e315b31307e1b15";
  }

  static const char* value(const ::grapebot_msgs::SteerState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95d8e1b9d9982300ULL;
  static const uint64_t static_value2 = 0x9e315b31307e1b15ULL;
};

template<class ContainerAllocator>
struct DataType< ::grapebot_msgs::SteerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grapebot_msgs/SteerState";
  }

  static const char* value(const ::grapebot_msgs::SteerState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grapebot_msgs::SteerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float32 CurrentSteerAngle\n\
float32 CurrentSensorRead\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::grapebot_msgs::SteerState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grapebot_msgs::SteerState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.CurrentSteerAngle);
      stream.next(m.CurrentSensorRead);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SteerState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grapebot_msgs::SteerState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grapebot_msgs::SteerState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "CurrentSteerAngle: ";
    Printer<float>::stream(s, indent + "  ", v.CurrentSteerAngle);
    s << indent << "CurrentSensorRead: ";
    Printer<float>::stream(s, indent + "  ", v.CurrentSensorRead);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPEBOT_MSGS_MESSAGE_STEERSTATE_H
